### ISSUE TITLE
[ROSThreadObj] Move from pthread to std::thread

### ISSUE THREAD

**Issue by alecive** [ScazLab/baxter_collaboration#43]
As per title. Ref #42

**Comment by sarimabbas** [comment]
For reference:

- Made a commit to feature/StdThreads branch: 8830202e4720a1f6fdda548f09549e6eba47b1b9
- While the rewritten ROSThreadObject code should work with existing test code (and it does so when inline with test code), it does not seem to compile when in separate files. 
- Now working on removing use of ROSThreadObj from code entirely

**Comment by alecive** [comment]
For the record: after https://github.com/ScazLab/baxter_collaboration/pull/47 has been merged and successfully tested, now @sarimabbas will proceed onto removing both `ROSThread` and `ROSThreadObject` classes from the repository altogether.

This will affect the following repositories, that need to be tested accordingly:
 * [baxter_collaboration](https://github.com/ScazLab/baxter_collaboration) , ie this one
 * [baxter_tictactoe](https://github.com/ScazLab/baxter_tictactoe)
 * [baxter_react_control](https://github.com/ScazLab/baxter_react_controller)

**Comment by sarimabbas** [comment]
For the record:
* https://github.com/ScazLab/baxter_collaboration/pull/48 (affects arm_ctrl inside baxter_collaboration)
* https://github.com/ScazLab/baxter_tictactoe/pull/25 (affects ttt_controller and tictactoeBrain inside baxter_tictactoe)
* https://github.com/ScazLab/baxter_collaboration/pull/50 (affects ROSThreadImage and associated files inside baxter_collaboration)

Note that if https://github.com/ScazLab/baxter_collaboration/pull/50 goes through, then a change will be needed to the boardState in baxter_tictactoe since it uses ROSThreadImage.

**Comment by alecive** [comment]
Ok, #50 has been fixed, so now you can move on `baxter_tictactoe`! :sunglasses:

**Comment by sarimabbas** [comment]
The boardState change: https://github.com/ScazLab/baxter_tictactoe/pull/26
